### ISSUE TITLE
When share 1 photo it works fine, but when select 2 or more photos does not show icon app on bottom sheet to select share

### ISSUE THREAD

**Issue by dung0301** [ShoutSocial/share_handler#105]

**Comment by JoshJuncker** [comment]
On iOS, look at the readme for the NSExtensionActivationRule. It tells the operating system how many files it can handle at one time, specifically the subquery where .@count > 0. The default implementation in the readme and example should allow for multiple files, and works for me. Please reopen this issue if you go through that and still can't share more than 1 at a time.

**Comment by dung0301** [comment]
> On iOS, look at the readme for the NSExtensionActivationRule. It tells the operating system how many files it can handle at one time, specifically the subquery where .@count > 0. The default implementation in the readme and example should allow for multiple files, and works for me. Please reopen this issue if you go through that and still can't share more than 1 at a time.


I am ready set up but not working...
![Screenshot 2024-11-06 at 08 35 23](https://github.com/user-attachments/assets/0b809011-8df1-42ac-9b23-25ff51355f1c)

**Comment by JoshJuncker** [comment]
I haven't done it with those specific rules before. If you run the example app, does it work?

**Comment by dung0301** [comment]
> I haven't done it with those specific rules before. If you run the example app, does it work?

I am setting follow this post: "https://saileshdahal.com.np/sharing-media-from-external-to-flutter-app"
On android device, this run ok, but on IOS device, when I select only 1 image, this still work ok, when I select more 1 image not work
