### ISSUE TITLE
ios: Undefined symbol: async function pointer to share_handler_ios_models.ShareHandlerIosViewController

### ISSUE THREAD

**Issue by jimmyff** [ShoutSocial/share_handler#17]
Hi, i'm migrating from `receive_sharing_intent`

When I try to build my app I get the following build errors:
```
Undefined symbol: async function pointer to share_handler_ios_models.ShareHandlerIosViewController.(handleText in _E48DB9355F792D6AF47E6D0E54D5F698)(content: __C.NSExtensionItem, attachment: __C.NSItemProvider, index: Swift.Int) async throws -> ()
Undefined symbol: async function pointer to share_handler_ios_models.ShareHandlerIosViewController.(handleFiles in _E48DB9355F792D6AF47E6D0E54D5F698)(content: __C.NSExtensionItem, attachment: __C.NSItemProvider, index: Swift.Int) async throws -> ()
Undefined symbol: async function pointer to share_handler_ios_models.ShareHandlerIosViewController.(handleUrl in _E48DB9355F792D6AF47E6D0E54D5F698)(content: __C.NSExtensionItem, attachment: __C.NSItemProvider, index: Swift.Int) async throws -> ()
Undefined symbol: async function pointer to share_handler_ios_models.ShareHandlerIosViewController.(handleImages in _E48DB9355F792D6AF47E6D0E54D5F698)(content: __C.NSExtensionItem, attachment: __C.NSItemProvider, index: Swift.Int) async throws -> ()
Undefined symbol: async function pointer to share_handler_ios_models.ShareHandlerIosViewController.(handleVideos in _E48DB9355F792D6AF47E6D0E54D5F698)(content: __C.NSExtensionItem, attachment: __C.NSItemProvider, index: Swift.Int) async throws -> ()
Undefined symbol: async function pointer to share_handler_ios_models.ShareHandlerIosViewController.(handleData in _E48DB9355F792D6AF47E6D0E54D5F698)(content: __C.NSExtensionItem, attachment: __C.NSItemProvider, index: Swift.Int) async throws -> ()
```

Any guidance would be really appreciated.

Thanks!

**Comment by benPesso** [comment]
Did you try `flutter clean` and deleting the `~/Library/Developer/Xcode/DerivedData/` folder? It's likely that you just have old Pod data.

**Comment by sharokh1** [comment]
okey I got it to work, thx @benPesso
So this library requires IOS 14, but I refactored the swift code to run on older IOS versions and that also seems to work!

**Comment by sharokh1** [comment]
@JoshJuncker so there are three things

- check if the buildsettings of the extension and the runner target are the same
- set the iOS version to 14 in both targets
- an edit in the share_handler_ios.podspec 
replace this
`  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES', 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'i386' }`
with
`  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES', 'VALID_ARCHS[sdk=iphonesimulator*]' => 'x86_64' }`

I'm curious if this will solve the problem of your friend.

**Comment by benPesso** [comment]
> * set the iOS version to 14 in both targets

I'm not sure if this is relevant, as mine are set to target v12.

**Comment by sharokh1** [comment]
then how does it work for you ? the whole swift controller has 
`@available(iOS 14.0, *)`

**Comment by benPesso** [comment]
Sorry, meant to say 13...
```platform :ios, '13.0'```

**Comment by sharokh1** [comment]
That would not matter, as the share extension controller only works on iOS 14+ that is why I'm asking you to try to run your app on a device/simulator with iOS 13 or below. My expectation is that the share functionality will not work.

**Comment by benPesso** [comment]
I was going by what you said and referred to the fact that the constraint was not necessary for the build to succeed. I wouldn't know to speculate what devices it would run on or not (and I don't have an iOS device with a version old enough to test).
