### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by SergiiMytakii** [ShoutSocial/share_handler#2]
I followed all steps, after hitting 'share' extension redirects to the containing app, but it does not receive any data

**Comment by Shawn-sudo** [comment]
For me, the OS seemed to reject opening the main app in a share extension (iOS). Probably this is another issue.

**Comment by JoshJuncker** [comment]
@SergiiMytakii What platform are you running on? And are you using actual device or simulator? Are you not getting any data on initial load from the getInitialSharedMedia? Or are you not getting anything from listening to the stream when your app is already open? If you download the repo and run the example, does the example work for you?
Anyways, just more information Ould be helpful.

**Comment by JoshJuncker** [comment]
@Shawn-sudo Did you make sure to follow the first step for iOS implementation?
```<!-- Add for share_handler start -->
<!-- The 'NSUserActivityTypes' key is only needed if you plan to use the recordSentMessage API allowing for conversations to show up as direct share suggestions -->
<key>NSUserActivityTypes</key>
<array>
    <string>INSendMessageIntent</string>
</array>
<key>CFBundleURLTypes</key>
<array>
    <dict>
        <key>CFBundleTypeRole</key>
        <string>Editor</string>
        <key>CFBundleURLSchemes</key>
        <array>
            <string>ShareMedia-$(PRODUCT_BUNDLE_IDENTIFIER)</string>
        </array>
    </dict>
    <dict/>
</array>

<key>NSPhotoLibraryUsageDescription</key>
<string>Photos can be shared to and used in this app</string>
<!-- Add for share_handler end -->```
It registers the deep link that is used by the plugin to open the app on redirect.
Anyways, if that doesn't work, please submit that is a separate issue. And check out the example to see if it runs for you.

**Comment by Phmichau** [comment]
Work great now. thank you

**Comment by JoshJuncker** [comment]
@dimitchik On a real iOS device, what are you trying to share? Can you try sharing different things? Like a website from Safari, or an image from Photos. Can you also run a flutter doctor so I can see the versions you are using?

**Comment by dimitchik** [comment]
Got the example project running after editing  podfile (didn't notice it's in .gitignore).
The issue seems to be with the xcode setup after all, I'll update here after i find out more.

**Comment by dimitchik** [comment]
OK, so I finally got it working! What fixed the problem for me was adding share_handler_ios to pubspec.yaml, so it has both share_handler and share_handler_ios. Can't reproduce this issue on other projects though, so not sure what even causes it.

**Comment by BrianMwas** [comment]
I tried everything even the example app but it did not run in my physical device. Am running an Oppo

**Comment by BrianMwas** [comment]
Not sure what am missing

**Comment by JoshJuncker** [comment]
@BrianMwas What is an "Oppo"? And what physical device? Also what flutter version?

**Comment by BrianMwas** [comment]
Oppo is a phone brand just like Samsung am using Flutter v2.10.5. So it works with every other export except WhatsApp which was what I am working on

**Comment by JoshJuncker** [comment]
@BrianMwas Just to clarify, sharing to your app is working when shared from other apps, like photos or drive, but not from WhatsApp?

**Comment by BrianMwas** [comment]
Yes

**Comment by BrianMwas** [comment]
Any update @JoshJuncker

**Comment by JoshJuncker** [comment]
@BrianMwas Sorry. I haven't had time recently and I don't use WhatsApp. I might be able to look into it today though.

**Comment by ultimate-tester** [comment]
Same issue here, trying to share a contact. App opens fine, but stream and initial function do not return anything..

**Comment by JoshJuncker** [comment]
@ultimate-tester Are you sharing all of these things from WhatsApp? If not, what apps are you sharing them from?

**Comment by ultimate-tester** [comment]
> @ultimate-tester Are you sharing all of these things from WhatsApp? If not, what apps are you sharing them from?

Thanks for the quick response. I’m sharing from the native app on iOS for the corresponding categories:

Contacts app, Photos app, Notes app, Safari.
I think I tested the plain text from Safari as well, simply selecting some text and hitting share.

Having just tested WhatsApp (hold a message, forward, share), that also doesn’t work. Seems like nothing comes in at the flutter side.

**Comment by JoshJuncker** [comment]
@ultimate-tester Interesting. I can't reproduce the notes (plain text) and safari (url) issue. Those share just fine for me on iOS. I'd make sure to follow the instructions carefully, or clone the repo and try the example project. 
However, sharing a contact (v-card) didn't work for me, so I'll have to look into that.

**Comment by giorgio79** [comment]
Just installed the iOS example app on an a simulator: iOS 11 13.7, but the app does not appear in share targets when highlighting text in Safari and trying to share it to the app... Any tips please? :)

**Comment by giorgio79** [comment]
PS Just tried this one and the example works out of the box on iOS Simulator 11 13.7. Hopefully we can lift some code from there to this app ;) https://github.com/JaimilPatel/ReceiveSharing
