### ISSUE TITLE
Not working for Release builds on iOS

### ISSUE THREAD

**Issue by aaronvargas** [ShoutSocial/share_handler#24]
Hey Great work on the Project! 

I'm having an issue that in XCode Debug builds work correctly. As in
1. my the app opens when Shared to
2. The sharedMediaStream has the SharedMedia

But for a Release build (changed by menu -> Product -> Scheme -> Edit Scheme and changing the 'build configuration' to Release)
I get my app opening, but the sharedMediaStream doesn't get anything

Another issue (perhaps unrelated) is when deploying my app in Android Studio (for debug), the first Share works correctly, but subsequent shares of different urls (from a browser for example) continue to share the first Shared url (not the one I just shared).

Thanks! Any Help appreciated.

If you are unable to repo happy to provide more details

**Comment by aaronvargas** [comment]
Turns out I had a mismatch in the group names between Debug and Release schemes. Needed to create additional `Runner.entitlements` and `ShareExtension.entitlements` variants to fix it. 

If I have additional difficulties with the 'subsequent shares from Android Studio', I'll make another issue.

Keep up the great work!

**Comment by abdu292** [comment]
@aaronvargas Thanks for letting us know. Does this mean we need entitlements for each configuration? I have a similar issue. It shows my app as a share target on debug mode, but after publishing (in release mode), my app is not at all appearing as a share target. It'd greatly help if you have some input. Thanks a bunch!
(I tested on iPhone 6s, iOS 15.8)

**Comment by abdu292** [comment]
Great. Thanks @aaronvargas for the response. This is much appreciated.
I'll try this!
