### ISSUE TITLE
Can't recieve coming from Contacts

### ISSUE THREAD

**Issue by osmantuzcu2** [ShoutSocial/share_handler#31]
I'm handling a vcf file when I tap on share contact on android side. However, on the IOS side, the media is empty. I shared a screenshot. There is no file or string in media value. 

<img width="680" alt="issue" src="https://user-images.githubusercontent.com/29891172/188270310-0ef64a60-da29-4af7-a450-6bce5d35eb8a.png">

**Comment by cto-leaps** [comment]
Hey @osmantuzcu2 , did you find a way to solve this by any chance?
I have the same issue...
