### ISSUE TITLE
[iOS] Crashes the app when shared and not in the background

### ISSUE THREAD

**Issue by oliverbytes** [ShoutSocial/share_handler#32]
It only works when the app is running in the background. Crash logs: 
[crash_logs.zip](https://github.com/ShoutSocial/share_handler/files/9579465/crash_logs.zip)

**Comment by oliverbytes** [comment]
Just found out what's causing it. If there's no GoogleServices-Info.plist in /Runner then it crashes.

**Comment by chrallard** [comment]
The app still crashes, despite having a GoogleServices-Info.plist file in /Runner

**Comment by chrallard** [comment]
Update: I took a look at the crash logs from the iPhone itself, and there appears to be a EXC_BAD_ACCESS (SIGSEGV) exception. I'm not sure what to do with this info, but I feel it's worth sharing.
