### ISSUE TITLE
Unhandled Exception: Invalid argument(s): Illegal percent encoding in URI

### ISSUE THREAD

**Issue by 6ag** [ShoutSocial/share_handler#36]
Hello brother, when the shared file name is named in Chinese, an exception will occur.

**Comment by czredhat** [comment]
I have the same with diacritics.

**Comment by JoshJuncker** [comment]
@6ag Can you check using the latest master to see if the issue is resolved with a recent merged pull request?

**Comment by 6ag** [comment]
@JoshJuncker Thanks a lot, using the latest master has solved the problem.
