### ISSUE TITLE
iOS: App not showing up in share target dialog on real device but only in Emulator

### ISSUE THREAD

**Issue by technetsol** [ShoutSocial/share_handler#41]
Hi, 

i tried setting up the minimal example from the github readme to be able to share images / videos on both android and iOS devices into the flutter app.

On android is is working like a charm, no matter if running inside an emulator or a real attached device.

After following the iOS setup with creating the share extension, adding the group to both the runner and the share extension, i first tried to run the flutter app inside an iOS emulator (iOS 16.2). I could start the photos app, choose an image and in the share target dialog i could find the flutter app behind the "three dots". When clicking on it, it just went back to the photo inside the photos app, not opening the flutter app.

So i thought this might be an emulator issue and tried deploying it both on a device with iOS 12 and iOS 16, the app shows the screen when started directly, but i won't show up inside the share target dialog, neither directly, nor behind the "three dots".

Could you please tell me if i am missing something here that it works in the emulator but not a real attached device?

**Comment by gekosurf** [comment]
Minimum i found was 14.0 for app and extension

**Comment by JoshJuncker** [comment]
Closing in favor of previous comments.
