### ISSUE TITLE
Release 0.0.17

### ISSUE THREAD

**Issue by Tienisto** [ShoutSocial/share_handler#43]
Thank you for this nice package!

[LocalSend](https://github.com/localsend/localsend) is using this package successfully.

However, users complained that files with non-English characters could not be shared. So I needed to use a git version instead of the official one.

https://github.com/localsend/localsend/blob/62ca72034df95018079488138ae8c3fe2a29213b/pubspec.yaml#L70

This fix did not break anything else, so it would be nice to release it so other developers won't run into the same problem.

**Comment by JoshJuncker** [comment]
Just released 0.0.17 :)
