### ISSUE TITLE
[Android] Can't not receive file from Files/Recent or Files/Documents on Android 11, 12 (API 30 -> 33)

### ISSUE THREAD

**Issue by duypxd** [ShoutSocial/share_handler#52]
- on `Android 10 (API 29)` I get file `image/pdf/docs/xlsx/txt` from `Files/Recent & Files/Download,...`
- But on `Android 11 (API 30)` # `Android 12 & 13 (API 30 -> 33)` I only get files from `Files/download`.
Paths like `Files/Recent` or `Files/Documents` then my `SharedMedia.attachments = null`

**Comment by duypxd** [comment]
Hi @JoshJuncker, do you have any solution for this problem?

**Comment by JoshJuncker** [comment]
@duypxd Not that I know of. I probably won't be able to look into it for a while as I have other priorities at work now. Sorry!

**Comment by duypxd** [comment]
yes @JoshJuncker , if you have time please take a look. I fixed the [crash on Android](https://github.com/ShoutSocial/share_handler/pull/51), but the `media.attachments = null` not work, is still looking for a way. Thanks :D

**Comment by lokishengoku** [comment]
I have same issue
