### ISSUE TITLE
can not work on ios 16 release model

### ISSUE THREAD

**Issue by zohar-soul** [ShoutSocial/share_handler#55]
Everything is well on iOS 15 using the example [example](https://github.com/ShoutSocial/share_handler/tree/main/share_handler/example) but no messages can be received on iOS 16

**Comment by zohar-soul** [comment]
appGroup Forgot to add release mode.
Be sure to double check. 😭

**Comment by niuhuan** [comment]
How to add release mode? There has no something 

![image](https://github.com/user-attachments/assets/0fe48233-1ed5-4741-9132-f6355c7eeb4c)
