### ISSUE TITLE
iOS recordSentMessage & flavors issue

### ISSUE THREAD

**Issue by PeterOmbodi** [ShoutSocial/share_handler#57]
I have `prod` and `dev` flavors in my project, and there is a certain problem with them. 
Share works for builds with both flavors, but `recordSentMessage `only works for prod env. 
Conditionally I have app bundles `com.bla.bla` , `com.bla.bla.dev` and groups `group.com.bla.bla`+`group.com.bla.bla.dev`. 
For build with `prod` env, `recordSentMessage` works well, I see my records in share recent section.
However, when using `recordSentMessage` in a build with the `dev` flavor, the section for recently sent messages does not show any records for this build, despite the terminal log containing the entry "_Successfully dontated INSendMessageIntent._" 
Is it possible to get some guidance on how to resolve this issue?

**Comment by PeterOmbodi** [comment]
My problem was resolved, but I don't know how exactly. I haven't changed anything in the code related to sharing flow, but it's magically started to work as expected). The only thing that I have done, I updated Flutter from  3.7.10 to 3.10.4 and bumped several libraries' versions to resolve dependencies conflicts.

**Comment by sajanIocod** [comment]
hi @PeterOmbodi did you use a different team in iOS for different flavors or not?

**Comment by PeterOmbodi** [comment]
Hi @sajanIocod I used the same account for both flavors
