### ISSUE TITLE
IOS on clicking app from share sheet not opening the app just the zoom out animation

### ISSUE THREAD

**Issue by amalshyjo** [ShoutSocial/share_handler#63]
So the app is showing in the share sheet but on clicking it does not lead to the app this is working perfectly on android. This behaviour is same for text and image. i am not a IOS developer 

https://github.com/ShoutSocial/share_handler/assets/56060390/478da718-07f2-4e91-bcb1-05670d1b939e

<img width="715" alt="Screenshot 2023-07-27 at 6 04 14 PM" src="https://github.com/ShoutSocial/share_handler/assets/56060390/b9a627be-a5aa-4899-a6f6-adcd952ae293">
<img width="700" alt="Screenshot 2023-07-27 at 6 04 08 PM" src="https://github.com/ShoutSocial/share_handler/assets/56060390/25399c4c-9daf-47a4-8676-cc780b10c060">

My code i have followed the readme 
info.plist
```
...
		<key>CFBundleURLTypes</key>
		<array>
			<dict>
				<key>CFBundleTypeRole</key>
				<string>Editor</string>
				<key>CFBundleURLSchemes</key>
				<array>
					<string>ShareMedia-$(PRODUCT_BUNDLE_IDENTIFIER)</string>
				</array>
			</dict>
		</array>
....
		<key>NSPhotoLibraryUsageDescription</key>
		<string>This app uses file storage for debug purpose</string>
...
```

Pubspec.yaml
`  share_handler: ^0.0.17`

ShareExtension.entitlements
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.application-groups</key>
	<array>
		<string>group.###</string>
	</array>
</dict>
</plist>
```

Podfile
```
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # Add this block
  target 'ShareExtension' do
    inherit! :search_paths
    pod "share_handler_ios_models", :path => ".symlinks/plugins/share_handler_ios/ios/Models"
  end
  # End of block

end
```

ShareExtension > Info.plist
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>CFBundleVersion</key>
    <string>$(FLUTTER_BUILD_NUMBER)</string>
    <key>NSExtension</key>
    <dict>
      <key>NSExtensionAttributes</key>
      <dict>
        <key>IntentsSupported</key>
        <array>
          <string>INSendMessageIntent</string>
        </array>
        <key>NSExtensionActivationRule</key>
        <dict>
          <key>NSExtensionActivationSupportsWebURLWithMaxCount</key>
          <integer>1</integer>
          <key>NSExtensionActivationSupportsWebPageWithMaxCount</key>
          <integer>1</integer>
          <key>NSExtensionActivationSupportsImageWithMaxCount</key>
          <integer>1</integer>
          <key>NSExtensionActivationSupportsFileWithMaxCount</key>
          <integer>1</integer>
          <key>NSExtensionActivationSupportsAttachmentsWithMaxCount</key>
          <integer>1</integer>
          <key>NSExtensionActivationSupportsText</key>
          <true />
        </dict>
        <key>PHSupportedMediaTypes</key>
        <array>
          <string>Image</string>
        </array>
      </dict>
      <key>NSExtensionMainStoryboard</key>
      <string>MainInterface</string>
      <key>NSExtensionPointIdentifier</key>
      <string>com.apple.share-services</string>
    </dict>
  </dict>
</plist>
<img width="700" alt="Screenshot 2023-07-27 at 6 04 08 PM" src="https://github.com/ShoutSocial/share_handler/assets/56060390/433d2a56-d8dc-46e7-a3e8-2f1ca85bea4b">

```

ShareViewController
class ShareViewController: ShareHandlerIosViewController {}

```

**Comment by jamescardona11** [comment]
Are you using a custom group?

**Comment by amalshyjo** [comment]
> Are you using a custom group?

No, i haven't used custom group 
i also used the following package - https://pub.dev/packages/receive_sharing_intent
the result are the same

**Comment by jamescardona11** [comment]
@amalshyjo Sorry, I tested different ways, and I can't replicate it.

**Comment by ShaggyGettu** [comment]
Hi @amalshyjo, having the same problem, are you maybe using different Bundle Identifier for every environment?

**Comment by gekosurf** [comment]
Have you added the group in your develop account settings?  It needs to be enabled for the bundle.   Also the share _intent needs a bundle name with an enxtension 
 id of some sort:
- bundlename.somenewname

**Comment by amalshyjo** [comment]
sorry for the late reply,
@ShaggyGettu no its a single bundle identifier for every environment 
@gekosurf i didn't full get what i should could you explain it more, as i do not have much idea about IOS development

**Comment by mny459** [comment]
```
<key>AppGroupId</key>
<string>group.myGroupId</string>
```

I had same problem. And I fix this by add top code to both Runner and ShareExtension Info.plist

**Comment by amalshyjo** [comment]
> ```
> <key>AppGroupId</key>
> <string>group.myGroupId</string>
> ```
> 
> I had same problem. And I fix this by add top code to both Runner and ShareExtension Info.plist

oh so create group id and connect to the app right, wait is this a custom group id @mny459

**Comment by mny459** [comment]
> > ```
> > <key>AppGroupId</key>
> > <string>group.myGroupId</string>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I had same problem. And I fix this by add top code to both Runner and ShareExtension Info.plist
> 
> oh so create group id and connect to the app right, wait is this a custom group id @mny459

I am not sure which is custom or default group id. I am not a iOS developer. But I could tell you is I just replase `<string>$(CUSTOM_GROUP_ID)</string>` to my real group id, then everything works.

**Comment by MuhammedRefaat** [comment]
@ShaggyGettu I'm using a bundle identifier for each environment, any clue?

**Comment by Rishab-ms** [comment]
@amalshyjo did it work?

**Comment by udiedrichsen** [comment]
Not for me, I have a custom group.

**Comment by The-Nils** [comment]
nothing work for me for both custom and default group

**Comment by udiedrichsen** [comment]
> I had the same problem. I discovered that the Minimum Deployments for the ShareExtension was set to iOS 17.0. After I reduced it to iOS 14.0, it worked.
> 
> In Xcode: Targets -> ShareExtension -> General -> Minimum Deployments -> iOS 14.0.
> 
> I hope it helps.

Cool, this works for me on a real device but not on a simulator.

**Comment by 842787863** [comment]
> ```
> <key>AppGroupId</key>
> <string>group.myGroupId</string>
> ```
> 
> 我有同样的问题。我通过向 Runner 和 ShareExtension Info.plist 添加顶级代码来解决此问题

Thanks, although I am not a custom group, this method helped me solve the problem

**Comment by JoshJuncker** [comment]
Closing as it is an Xcode configuration issue that people seem to have solved. If there are other issues, please open a new issue with details. Thank you!
