### ISSUE TITLE
[feature want] support action extension 

### ISSUE THREAD

**Issue by Liloupar** [ShoutSocial/share_handler#64]
Can iOS action extension  be supported?

Thank you.

**Comment by Liloupar** [comment]
resolved

**Comment by xiejibiao** [comment]
@Liloupar May I ask how you achieved it?

**Comment by Liloupar** [comment]
> [@Liloupar](https://github.com/Liloupar) May I ask how you achieved it?

创建个类型是action的target, 其余照抄share_handler的iOS模块即可

**Comment by xiejibiao** [comment]
@Liloupar 我尝试过创建一个action 的模块， 但是始终是不生效，我还是没有看到有我的action
