### ISSUE TITLE
Actual documentation

### ISSUE THREAD

**Issue by gisborne** [ShoutSocial/share_handler#65]
A lot of details about how to use this are left as an exercise for the reader.

There is both attachments and content. There are video, image, audio, file types of attachments.

So what do I get in various scenarios? Say, the user shares a web page. I assume I get the URL? As… content?

Might I sometimes get content without any attachments? What about a content and multiple attachments?

What sort of situations will give me multiple attachments? Should I try to prefer one of these as being richer?

And this recordSentMessage business. I've no idea what that is about.

**Comment by JoshJuncker** [comment]
Good feedback. Feel free to try it out and make a pull request with some more documentation for the different scenarios.
