### ISSUE TITLE
How to route to custom page?

### ISSUE THREAD

**Issue by chris-yeung** [ShoutSocial/share_handler#83]
In the example, it works when share content to the app.
But how to share content with directing to open app and route to certain page?

I try place the ShareHandler in the second page, but after i click share, the app open, but it still is the first page, however, when i go second page, i see the file, but what i want is direct to second page. 

Thank you, is anyone has idea of this?

  Future<void> initPlatformState() async {
    final handler = ShareHandler.instance;
    media = await handler.getInitialSharedMedia();

    print("media---");
    handler.sharedMediaStream.listen((SharedMedia media) {
      print(media);
      if (!mounted) return;
      setState(() {
        this.media = media;
      });
    });
    if (!mounted) return;

    setState(() {
      // _platformVersion = platformVersion;
    });
  }

**Comment by Mounix99** [comment]
Check the example in [this video](https://www.youtube.com/watch?v=6bWW6EMEIXY&t=406s)

**Comment by JoshJuncker** [comment]
Closing this assuming you figured it out with that video. Please open it again if you have more questions or think there is an issue.
