### ISSUE TITLE
Receive a sharing intent without opening the app

### ISSUE THREAD

**Issue by maelchiotti** [ShoutSocial/share_handler#90]
Hi, I would like to process the shared data (copy it to the clipboard) without opening the app. Is it possible?

**Comment by JoshJuncker** [comment]
I'm not sure I understand your need. In iOS, the share sheet usually gives a 'copy image' or 'copy' button as an option, rather than selecting an app to share to.

**Comment by maelchiotti** [comment]
Some Android ROMs do not, such as MIUI 13 (yes that's very stupid and annoying).

So I use an app, to which I share the content, and that app copies it to the clipboard for me. So I wanted to recreate it myself.

**Comment by JoshJuncker** [comment]
Gotcha. You might be able to do that. But not with this plugin. You could use the plugin as a base though and build off of it. Basically edit the android ShareHandlerPlugin.kt to copy info to the clipboard. And then maybe close the app?

**Comment by maelchiotti** [comment]
Thank you. Don't know if I will take the time to do it, but if I do I'll let you know

**Comment by maelchiotti** [comment]
You can close the issue I guess, you answered it ☺️
